Wrist subsystem
Frc5572/FRC2023 pull request #38
Opened 2023-02-02 23:11 UTC by gvaldez7206

2023-02-04 00:03 UTC, legoguy1000 requested changes

2023-02-04 00:03 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/WristAlignment.java
> +    public WristAlignment(Wrist wristAlignment) {
rename wristAlignment, makes no sense

2023-02-04 00:03 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/WristAlignment.java
> +public class WristAlignment extends CommandBase {
How is this command different from WristMovement??

2023-02-04 00:03 UTC, legoguy1000 commented on src/main/java/frc/robot/modules/Vision.java
> +public class Vision {
Delete this

2023-02-04 00:03 UTC, legoguy1000 commented on src/main/java/frc/robot/RobotContainer.java
> +        operator.a().whileTrue(new WristMovement(wrist, -0));
whats the difference?

2023-02-25 00:10 UTC, agrinmanriv0537 approved these changes

2023-02-25 00:10 UTC, legoguy1000 approved these changes

2023-02-25 00:10 UTC, merged