Elevator subsystem
Frc5572/FRC2023 pull request #40
Opened 2023-02-03 00:12 UTC by gvaldez7206

2023-02-03 23:57 UTC, legoguy1000 requested changes

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    private CANSparkMax motor2 = Elevator.rightElevatorMotor;
This should only be defined within subsystem

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    private DutyCycleEncoder dutyCycleEncoder = Elevator.elevatorEncoder;
This should only be defined within subsystem

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +        this.encoderGoal = rotation;
Missing subsystem argument.
Missing addRequirements()

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +        Elevator.runMotor(encVal(), encoderGoal);
should be a class variable from constructor

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    }
Should be in subsystem

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    }
no () needed

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Elevator.java
> +        rightElevatorMotor.set(elevatorPID.calculate(currentVal, goal));
only 1 motor per Mr Rucinski

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Elevator.java
> +        new CANSparkMax(Constants.Elevator.rightElevatorMotorID, MotorType.kBrushless);
only 1 motor per Mr Rucinski

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Elevator.java
> +        Constants.Elevator.elevatorKVVoltsSecondsPerRotation);
not using feed forward

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Elevator.java
> +        new CANSparkMax(Constants.Elevator.rightElevatorMotorID, MotorType.kBrushless);
Should be private

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/subsystems/Elevator.java
> +    public static final DutyCycleEncoder elevatorEncoder = new DutyCycleEncoder(99);
should be private

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    }
This doesn't make sense, when does encoderGoal ever change from initial set? Will this ever trigger? no ()

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +        motor2.set(0);
1 motor

2023-02-03 23:57 UTC, legoguy1000 commented on src/main/java/frc/robot/commands/MoveElevator.java
> +    private CANSparkMax motor2 = Elevator.rightElevatorMotor;
only 1 motor

2023-02-27 22:56 UTC, owenflatman approved these changes
Looks good 👍

2023-02-27 22:57 UTC, legoguy1000 approved these changes

2023-02-27 22:57 UTC, merged